services:
  migrate:
    build:
      context: .
      target: migrate-final
    image: magnet-feed-sync-migrate:local

  magnet-feed-sync:
    build:
      context: .
      target: final
    image: magnet-feed-sync:local
