services:
  magnet-feed-sync:
    container_name: magnet-feed-sync
    build:
      context: .
      target: final
    restart: unless-stopped
    environment:
      SYNOLOGY_URL: ${SYNOLOGY_URL}
      SYNOLOGY_USERNAME: ${SYNOLOGY_USERNAME}
      SYNOLOGY_PASSWORD: ${SYNOLOGY_PASSWORD}
      SYNOLOGY_DESTINATION: ${SYNOLOGY_DESTINATION}
      QBITTORRENT_URL: ${QBITTORRENT_URL}
      QBITTORRENT_USERNAME: ${QBITTORRENT_USERNAME}
      QBITTORRENT_PASSWORD: ${QBITTORRENT_PASSWORD}
      QBITTORRENT_DESTINATION: ${QBITTORRENT_DESTINATION}
      DOWNLOAD_CLIENT: ${DOWNLOAD_CLIENT}
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_SUPER_USERS: ${TELEGRAM_SUPER_USERS}
      BASE_STATIC_PATH: /static
      HTTP_PORT: 8080
    volumes:
      - .db:/.db
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.magnet-feed-sync.rule=Host(`magnet-feed-sync.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.magnet-feed-sync.entrypoints=https"
      - "traefik.http.routers.magnet-feed-sync.tls.certresolver=le"

networks:
  proxy:
    external: true
